# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb43014a87d6090df8b6b7a81e8a84097ed31de88d2a8487c34940f8eeee797552287013665661bd30e7875f21cca1ef79b55d6232487b4f2bcfa788e2cb48d2

test:
  secret_key_base: 14a6c515a18f4885d91cadaefddb274714bd01b8c31d08e4681908822efa5472e0f97623e8b3052932391343499ebfecbcd864d946e0471e8d8bf46e4e70087b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
